language: rust
language: node_js

rust:
    - 1.25.0

install:
    - npm install

cache: cargo
cache:
  directories:
    - "node_modules"

script:
    - cd client && npm run build
    - cargo build --verbose --all
    - cargo test --verbose --all
